# Generated by Django 5.1 on 2024-08-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('populacao', models.IntegerField()),
                ('regiao', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('populacao', models.IntegerField()),
                ('país', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapas_paises.paises')),
            ],
        ),
    ]
