# Generated by Django 5.1 on 2024-08-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas_paises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paises',
            name='populacao',
            field=models.CharField(max_length=255),
        ),
    ]
