# Generated by Django 5.1 on 2024-08-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas_paises', '0002_alter_cidade_populacao_alter_paises_populacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='populacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paises',
            name='populacao',
            field=models.IntegerField(),
        ),
    ]
